unique_ids:
  forms:
    main_frm: L7UHZH3O5ZYDGOUFG67P5S4ZKNY5LKVV
  modules: {}
  server_modules: {}
  assets:
    standard-page.html: C7HCINEQG65XM4Z3NPU4U3W2FZJRPFAJ
    theme.css: S25M5DE7USUAZ4S5MMDYPVGOP5BA7PHA
  scripts: {}
